-- Create the table structure
CREATE TABLE PERSONS (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        firstname VARCHAR(255) NOT NULL,
                        lastname VARCHAR(255) NOT NULL,
                        email VARCHAR(255) NOT NULL,
                        passport VARCHAR(255) NOT NULL
);

